### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by VenomousSteam81** [simply-devlop/simply-djs#88]
**Describe the bug**
Does not support DiscordJS v14

**To Reproduce**

1. Upgrade DiscordJS to v14

**Expected behavior**
Work fine

**Screenshots**

**Versions (please complete the following information):**

- Discord.js Version v14.5.0
- simply-djs Version Latest

**Additional context**
None

**Comment by Xx-Mohit-xX** [comment]
How its a issue/bug, where does it says have simply-djs supports discord.js v14. The support for djs v14 is work in progress and you can contribute in it too

**Comment by Xx-Mohit-xX** [comment]
How its a issue/bug, where does it says have simply-djs supports discord.js v14. The support for djs v14 is work in progress and you can contribute in it too
